# Generated by Django 6.0.5 on 2026-05-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('juzgado', models.TextField()),
                ('actor', models.TextField(blank=True, null=True)),
                ('demandado', models.TextField(blank=True, null=True)),
                ('juicio', models.TextField(blank=True, null=True)),
                ('id_carpeta_judicial', models.BigIntegerField(unique=True)),
                ('fecha_radicacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_imagen', models.BigIntegerField()),
                ('ruta', models.TextField()),
                ('archivo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='scraper.expediente')),
            ],
        ),
    ]
