# Generated by Django 6.0.5 on 2026-05-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id_imagen',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='NodoArbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_id', models.BigIntegerField()),
                ('label', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('cve_tipo_actuacion', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('id_formulario', models.CharField(blank=True, max_length=50, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='scraper.expediente')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='scraper.nodoarbol')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
