# Generated by Django 6.0.5 on 2026-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_documento_id_imagen_nodoarbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='referencia_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
