# Generated by Django 6.0.5 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_documento_referencia_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="expediente",
            name="materia",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]

